version: "3"

services:
  stream-sniff:
    build: .
    container_name: stream-sniff
    hostname: stream-sniff
    environment:
      APP_ENV: production
      HTTP_ADDRESS: ":8080"
      INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP: "yes"
    network_mode: "host"
    privileged: true
